<?php
/*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 * Developer Notes: Konstantinos Merentitis
 * Version History
 *        2017-06-28   11888.gr now needs https
 *	  2016-02-11   Initial release
  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***/

//Greek to Greeklish script - thanx to Burned4
function greeklish($Name)

 {
$greek = array('α','ά','Ά','Α','β','Β','γ', 'Γ', 'δ','Δ','ε','έ','Ε','Έ','ζ','Ζ','η','ή','Η','θ','Θ','ι','ί','ϊ','ΐ','Ι','Ί', 'κ','Κ','λ','Λ','μ','Μ','ν','Ν','ξ','Ξ','ο','ό','Ο','Ό','π','Π','ρ','Ρ','σ','ς', 'Σ','τ','Τ','υ','ύ','Υ','Ύ','φ','Φ','χ','Χ','ψ','Ψ','ω','ώ','Ω','Ώ'); 
$english = array('a', 'a','A','A','b','B','g','G','d','D','e','e','E','E','z','Z','i','i','I','th','TH', 'i','i','i','i','I','I','k','K','l','L','m','M','n','N','x','X','o','o','O','O','p','P' ,'r','R','s','s','S','t','T','u','u','Y','Y','f','F','ch','CH','ps','PS','o','o','O','O',); 
$string  = str_replace($greek, $english, $Name);
return $string;
 }

class 11888_GR_lookup extends superfecta_base {

 public $description = "11888 - Greece Reverse Phone Lookup";
    public $version_requirement = "2.11";
    function get_caller_id($thenumber, $run_param=array()) {
        $caller_id = null;
        $url = "https://www.11888.gr/list-names?_wpType=number&_wpPhone=$thenumber";
        $pattern = '/title"\>(.*)\<\/span>/U';

            if ($this->SearchURL($url, $pattern, $match)) {
                $caller_id = $this->ExtractMatch($match);
                $caller_id = greeklish($caller_id);
                $caller_id = substr($caller_id, 0, 35);
		// Optional: convert to title case:
	        // $caller_id = ucwords(strtolower($caller_id));
        }
	return($caller_id);
    }

}
